### ISSUE TITLE
我在打ab包的时候勾选AppendHash，但是UI加载失败，因为ab包名加了hash值

### ISSUE THREAD

**Issue by Ganlei4052** [SaiTingHu/HTFramework#13]
我在打ab包的时候勾选AppendHash，但是UI加载失败，因为ab包名加了hash值，UI逻辑类标记的AssetBundleName好像没法加hash值，因为不确定这个值，我在用微信官方提供的转换小游戏工具，它的缓存机制需要ab包打包设置BuildAssetBundleOptions.AppendHashToAssetBundleName，这个我应该怎么处理好呢。

**Comment by SaiTingHu** [comment]
UI的AssetBundleName只是为了识别到对应的ab包的文件名，只要与文件名一样就行

**Comment by Ganlei4052** [comment]
> UI 的 AssetBundleName 只是为了识别到对应的 ab 包的文件名，只要与文件名一样就行
但是勾选AppendHash之后ab包文件名会带上一串hash值呢，然后这个值是Unity生成的，我不知道怎么去匹配文件名呢，不过我改成AddressablesAsset方案解决这个问题了，大神有交流群吗？
