### ISSUE TITLE
我如果修改了打包方法,做了AB包加密,是否只能自己实现DefaultResourceHelper,无法实现加载进度条了?

### ISSUE THREAD

**Issue by zhangboyanzhangboyan** [SaiTingHu/HTFramework#16]
我打AB包的时候做了Offset加密，官方的加载方式是
```
//第三个参数是Offset,这样就完成了解密并加载
AssetBundle assetBundle = AssetBundle.LoadFromFile(filePath, 0, 2);
```

但默认的资源加载助手采用的是UnityWebRequestAssetBundle.GetAssetBundle的实现方式
而这种方式不支持传入Offset参数进行解密加载

那我是否只能自己实现ResourceHelper,这样就无法使用加载进度条了

**Comment by zhangboyanzhangboyan** [comment]
@SaiTingHu 好的,我已经改成了自定义的ResourceHelper,修改了LoadAssetBundleAsync的`UnityWebRequestAssetBundle.GetAssetBundle`方法

但`isManifest`这个参数就用不到了,不会有什么影响吧

![图片](https://github.com/SaiTingHu/HTFramework/assets/25657700/17de81b2-0cdd-444d-92f5-0cf778f7c3a5)

**Comment by SaiTingHu** [comment]
isManifest表示是否是加载清单文件，如果不是（则为正式AB包），会使用hash值校验，这个应是UnityWebRequestAssetBundle特有的机制，你直接从文件Load包，应该是不需要这个校验过程了

**Comment by zhangboyanzhangboyan** [comment]
好的，感谢
