### ISSUE TITLE
UI管理器，数据驱动功能绑定TMP的组件，未同步数据的问题

### ISSUE THREAD

**Issue by CrazyangSeeYou** [SaiTingHu/HTFramework#21]
![截图](https://github.com/SaiTingHu/HTFramework/assets/42412011/f4f16feb-90df-4349-9f0c-78543c64bc9c)
![截图2](https://github.com/SaiTingHu/HTFramework/assets/42412011/3c350c86-fd3f-416d-9105-c30c7164c847)

大佬，我在使用贵框架进行数据驱动，绑定了UGUI的Text和Input组件，可以进行同步数据，但是绑定TMP的Text和Input组件，无法数据同步，望大佬看一下什么问题

**Comment by SaiTingHu** [comment]
目前不支持TMP，后续会考虑加入

**Comment by CrazyangSeeYou** [comment]
好的，感谢回复

**Comment by CrazyangSeeYou** [comment]
期待后续更新

**Comment by SaiTingHu** [comment]
[commit](https://github.com/SaiTingHu/HTFramework/commit/890afd72b15320b49963365a5c094c42b411bf1f)
