### ISSUE TITLE
是否可以将UI元素注入UIRegion？

### ISSUE THREAD

**Issue by refiavridis** [SaiTingHu/HTFramework#24]
UIRegion中是否可以通过反射（或其他方式）得到当前UI的元素？
类似 `[InejctPath("")]` 的方式。

虽然在UIRegion中可以通过 Parent 获取当前UI，但业务逻辑定义和UI注入处在不同的地方，可能解耦得不够彻底。

感谢您的解答！

**Comment by SaiTingHu** [comment]
谢谢提议，这确实是一个疏漏，将在后续改进它

**Comment by refiavridis** [comment]
非常感谢！

**Comment by SaiTingHu** [comment]
[commit](https://github.com/SaiTingHu/HTFramework/commit/d7b7d0eaed17baf000f0246b2a04779059d9dce6)
