### ISSUE TITLE
 打包时为 AssetBundle 文件名称添加 Hash 时加载出错

### ISSUE THREAD

**Issue by unittt** [SaiTingHu/HTFramework#26]
![1](https://github.com/user-attachments/assets/35632700-9c05-4812-8b62-79c7ffd7249a)
![2](https://github.com/user-attachments/assets/46c31d24-64f1-424a-aa5d-36e798f9ccd9)

**Comment by SaiTingHu** [comment]
打完后，AB包重命名把hash删掉

**Comment by unittt** [comment]
> 打完后，AB包重命名把hash删掉

微信小游戏平台 需要在ab文件名中带资源hash，才可以在资源更新时，识别不同版本的资源。

**Comment by SaiTingHu** [comment]
使用 Addressables 模式：

![图片](https://github.com/user-attachments/assets/4b1ecf5e-130c-4049-b19d-69764b20e361)

参考链接1：[HTFramework框架（五十三）使用 Addressables 可寻址系统](https://wanderer.blog.csdn.net/article/details/140700085)
参考链接2：[HTFramework框架（五十五）只使用资源路径、资源名称加载资源](https://wanderer.blog.csdn.net/article/details/140875468)
