### ISSUE TITLE
什么 是RealProxy ？有没demo 可以看看

### ISSUE THREAD

**Issue by ErDon** [SaiTingHu/HTFramework#3]
Assets\HTFramework\RunTime\AspectTrack\Base\AspectProxyBase.cs(9,48): error CS0246: The type or namespace name 'RealProxy' could not be found (are you missing a using directive or an assembly reference?)

**Comment by SaiTingHu** [comment]
请参见Readme文档，框架需要环境.NET 4.x。

在如下路径设置：(Unity 2018.3.0) PlayerSettings -> OtherSettings -> Api Compatibility Level* 设置为.NET 4.x

**Comment by ErDon** [comment]
我已经是 .NET 4.x ，Unity版本Unity 2018.4.7f1 (64-bit) ，还有我把 预制件HTFramework 拖到场景中，Main 提示 授权已到期！

**Comment by SaiTingHu** [comment]
可以看看[这里](https://wanderer.blog.csdn.net/article/details/102956756)
