### ISSUE TITLE
Builder.cs 85-88有点问题

### ISSUE THREAD

**Issue by sunny2019** [SaiTingHu/HTFramework#4]

**Comment by SaiTingHu** [comment]
有什么问题？

**Comment by sunny2019** [comment]
OnBodyGUI()里面有段
if (EditorBuildSettings.scenes != null)
{
       EditorBuildSettings.scenes = null;
}
OnBodyGUI()在EditorWindow中的OnGUI事件内被调用
这样不就始终无法添加场景了嘛？

**Comment by SaiTingHu** [comment]
对的，这里是这样设计的，主程序只能发布包含Main的主场景，资源或其他场景都是动态加载，如要加载其他场景，可以将场景打入AB包再加载。
