### ISSUE TITLE
Are we support iOS platform yet?

### ISSUE THREAD

**Issue by takaaptech** [SaiTingHu/HTFramework#5]
Hi @SaiTingHu ,
HTFamework is an awesome framework to make Unity game. For now, is this support export game to ios yet?
Thank you
<img width="597" alt="Screen Shot 2020-04-03 at 10 33 37 AM" src="https://user-images.githubusercontent.com/6276251/78321664-cfcbb700-7596-11ea-864c-bb3a38c6e049.png">
!

**Comment by SaiTingHu** [comment]
maybe, I just said maybe, his support ios platform! （because I don't have any IOS devices to test this...⊙﹏⊙）

**Comment by takaaptech** [comment]
Then OK I just test and see that it can build and run!
I just wonder why we can not put the scene into the building setting window, is the framework auto select the scene with HTFramework prefab include?

**Comment by SaiTingHu** [comment]
Yes, we think this rule is more suitable to maintain: HTFramework prefab scene is the entrance, other things are done in this scene, it is not recommended to switch multiple scenes.
Of course,You also don't have to do it, this is only our rules, we use experience to prove that it is effective.

**Comment by takaaptech** [comment]
@SaiTingHu OK Just translate the log from the framework and understand that. If the framework force to do that, then thing more simply, I like that! I wish all the log content will have the English version. Sometimes Google Translate are very messing.
Thanks!
