### ISSUE TITLE
加载AssetBundle好像有问题

### ISSUE THREAD

**Issue by JasonCuizy** [SaiTingHu/HTFramework#7]
isManifest=false时，调用了GetAssetBundleHash方法，报NullReferenceException
代码：
UnityWebRequest request = isManifest
? UnityWebRequestAssetBundle.GetAssetBundle(AssetBundleRootPath + assetBundleName)
: UnityWebRequestAssetBundle.GetAssetBundle(AssetBundleRootPath + assetBundleName,GetAssetBundleHash(assetBundleName))

**Comment by SaiTingHu** [comment]
我没有遇到过这个问题，可以截图看下你ResourceManager面板的设置吗？还有AB包文件夹的整体结构图

**Comment by SaiTingHu** [comment]
我已补全了Resource的Demo [https://github.com/SaiTingHu/HTFrameworkDemo](url)，可以看下是否有相关设置错了
